version: '3.0'

services:
  prock.sample:
    image: procksample
    build:
      context: .
      dockerfile: src/Prock.Sample/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"